version: '3'
services:
  redis:
    image: redis
  subscriber:
    build:
      context: ./subscriber
      dockerfile: ./Dockerfile
    image: jeremyleo/python-redis-subscriber
    tty: true
    entrypoint: python app.py
    depends_on:
      - redis
  publisher:
    build:
      context: ./publisher
      dockerfile: ./Dockerfile
    image: jeremyleo/python-redis-publisher
    ports:
      - 8080:8080
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 8080
    depends_on:
      - redis
  worker:
      build:
        context: .
        dockerfile: ./celery/Dockerfile
      command: [ 'celery', '-A', 'app.app', 'worker', '-l', 'info' ]
      environment:
        - BROKER_URL=redis://redis:6379
        - RESULT_BACKEND=redis://redis:6379
      depends_on:
        - redis
  flower:
      image: mher/flower:0.9.7
      command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
      ports:
        - 5555:5555
      depends_on:
        - redis